# Generated by Django 5.0.1 on 2024-05-05 06:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("total_stock", models.PositiveIntegerField(default=100)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "medicine",
            },
        ),
        migrations.AlterField(
            model_name="medicalrecords",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 5, 8, 54, 23, 714823)
            ),
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_instructions", models.TextField()),
                ("medicine", models.CharField(max_length=200)),
                ("dosage", models.PositiveIntegerField()),
                ("prescription_time", models.TimeField(default=datetime.datetime.now)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.customer",
                    ),
                ),
            ],
            options={
                "db_table": "prescription",
            },
        ),
    ]
