# Generated by Django 5.0.1 on 2024-05-05 09:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_medicine_alter_medicalrecords_time_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecords",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 5, 11, 3, 37, 735653)
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="medication_instructions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointments.medicine"
            ),
        ),
    ]
