# Generated by Django 5.0.1 on 2024-05-05 09:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_alter_medicalrecords_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecords",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 5, 11, 9, 39, 171640)
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="medication_instructions",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointments.medicine"
            ),
        ),
    ]
