# Generated by Django 5.0.1 on 2024-05-05 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_alter_medicalrecords_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecords",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 5, 14, 49, 31, 538161)
            ),
        ),
    ]
