# Generated by Django 5.0.1 on 2024-05-05 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0007_alter_medicalrecords_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecords",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 5, 17, 29, 24, 946668)
            ),
        ),
    ]
