# Generated by Django 5.0.1 on 2024-05-12 16:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0009_alter_medicalrecords_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customer",
            name="claim_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_insurance",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="medicalrecords",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 12, 18, 37, 8, 215592)
            ),
        ),
        migrations.CreateModel(
            name="MedicalOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("medical_expense", models.FloatField()),
                ("is_claim", models.BooleanField(default=False)),
                ("is_pay", models.BooleanField(default=False)),
                (
                    "create_time",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 5, 12, 18, 37, 8, 232377)
                    ),
                ),
                (
                    "appointment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "medical_order",
            },
        ),
    ]
