# Generated by Django 5.0.1 on 2024-05-12 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0010_customer_balance_customer_claim_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="claim_rate",
        ),
        migrations.AlterField(
            model_name="medicalorder",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 12, 19, 3, 4, 585023)
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecords",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 12, 19, 3, 4, 585023)
            ),
        ),
    ]
