# Generated by Django 5.0.1 on 2024-05-12 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0011_remove_customer_claim_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalorder",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 12, 19, 27, 42, 154744)
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecords",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 12, 19, 27, 42, 154744)
            ),
        ),
    ]
